services:
  - type: web
    name: shraddhavideology
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: ADMIN_TOKEN
        value: sv-admin-2024-manav
      - key: NODE_ENV
        value: production
